# SpamView runtime environment — generated by installer
# See README.md for what each variable does.

# Mailserver to pull data from (mailcow host)
MAILSERVER_HOST=%%MAILSERVER_HOST%%
MAILSERVER_USER=%%MAILSERVER_USER%%
MAILSERVER_KEY=/var/lib/spamview/.ssh/id_ed25519

# Mailcow installation specifics
MAILCOW_PROJECT=%%MAILCOW_PROJECT%%
MAILCOW_PATH=%%MAILCOW_PATH%%

# Comma-separated regexes; matched against envelope_from + helo. Drops own-host
# notification noise that's expected to be rejected by postscreen.
IGNORE_HOSTS=%%IGNORE_HOSTS%%

# Optional: AI insights via Google Gemini (free tier sufficient for personal use)
# Get a key at https://aistudio.google.com/apikey, leave empty to disable.
GEMINI_API_KEY=%%GEMINI_API_KEY%%
GEMINI_MODEL=gemini-2.5-flash
